#: The basic colors

foreground                      #ffffff
background                      #252a33
selection_foreground            #000000
selection_background            #dbdee5


#: Cursor colors

cursor                          #ffffff
cursor_text_color               #252a33


#: URL underline color when hovering with mouse

url_color                       #a3be8c


#: kitty window border colors and terminal bell colors

active_border_color             #dbdee5
inactive_border_color           #3a3f48
bell_border_color               #f28b82
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #252a33
active_tab_background           #dbdee5
inactive_tab_foreground         #bebfc2
inactive_tab_background         #1e222a
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0  #1e222a
color8  #3a3f48

#: red
color1  #f28b82
color9  #f6a199

#: green
color2  #a3be8c
color10 #b6d09f

#: yellow
color3  #ebcb8b
color11 #f0d399

#: blue
color4  #81a1c1
color12 #95b0cb

#: magenta
color5  #b48ead
color13 #c8a4c1

#: cyan
color6  #88c0d0
color14 #9bcddb

#: white
color7  #dbdee5
color15 #e5e9f0


#: You can set the remaining 240 colors as color16 to color255.

color16 #f28b82
color17 #b48ead
